Update TestCompilation.yml
Qytera-Gmbh/QTAF pull request #75
Opened 2023-04-19 06:26 UTC by MoritzSalein

Changed the GitHub Action for executing QTAF on chrome and renamed the Action.

2023-04-19 13:49 UTC, csvtuda requested changes

2023-04-19 13:49 UTC, csvtuda commented on .github/workflows/TestCompilation.yml
While the changes are much appreciated, I think this action should undergo a total rework:
1. It does not make sense to run `mvn clean test` on push to both `main` and `develop`. The `main` branch is used only for backing up the latest release code, which never actually gets there without going through the tests run on release: https://github.com/Qytera-Gmbh/QTAF/blob/0b40bfb043b7ae17a56e69917afe697e34d2ed5d/.github/workflows/PublishMavenCentral.yml#L36-L51 This job should probably be moved into its own action that runs tests when trying to merge a pull request into `develop`.
3. I would much prefer a matrix approach for building the docker images to reduce code duplication. Something like this:
```yml
  build_java_image:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.TIMEOUT_MINUTES }}
    strategy:
      matrix:
        version: [ 17, 18, 19 ]
        include:
          - version: 17
            command: sh ./scripts/docker/build-java17-image.sh
          - version: 18
            command: sh ./scripts/docker/build-java18-image.sh
          - version: 19
            command: sh ./scripts/docker/build-java19-image.sh
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build docker image
        run: ${{ matrix.command }}
```

2023-04-19 15:01 UTC, MoritzSalein commented
@csvtuda Do you think the new version of the Action could work?

2023-04-19 21:33 UTC, csvtuda commented on .github/workflows/TestCompilation.yml
> +          - 4445:4444
Nit: I think we could also do 
```yml
ports:
  - ${{ matrix.port }}:4444
```
here (not quite sure), but it's fine as is.

2023-04-19 21:40 UTC, csvtuda commented
Looks good to me! I think we should switch to the reusable unit test action as well for the testing part, though.
- Unit test action: https://github.com/Qytera-Gmbh/QTAF/blob/eecf699f67a37cfec22f059db5da4fad8ab5ab02/.github/workflows/Test.yml
- Example call: https://github.com/Qytera-Gmbh/QTAF/blob/eecf699f67a37cfec22f059db5da4fad8ab5ab02/.github/workflows/Publish.yml#L13-L17

I think providing a remote driver doesn't really affect QTAF's unit tests, I've never had to provide it. So it should probably be fine to switch to the test action.

2023-04-20 06:35 UTC, MoritzSalein commented
I tried to insert the reusable test Action in my Action. Also I renamed it, to clarify that it only runs on the develop branch.

2023-04-20 15:55 UTC, csvtuda approved these changes

2023-04-21 14:43 UTC, merged